# cargo

# [[file:~/Workspace/Programming/gchemol-rs/nxgraph/nxgraph.note::*cargo][cargo:1]]
[package]
name = "nxgraph"
version = "0.0.1"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
petgraph = "0.4"
guts = { git = "https://github.com/ybyygu/guts.git" }

[dev-dependencies]
# cargo:1 ends here
